name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test tests/smoke.spec.ts

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # 🟢 ЕСЛИ ВСЁ ПРОШЛО УСПЕШНО:
    - name: Send Telegram Success Notification
      if: success()
      run: |
        TEXT="✅ *Playwright Tests PASSED!*%0A%0A👤 *Автор:* ${{ github.actor }}%0A🌿 *Ветка:* ${{ github.ref_name }}%0A📝 *Коммит:* ${{ github.event.head_commit.message }}%0A%0A🚀 Проект стабилен!"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOK }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_TO }}" \
          -d text="$TEXT" \
          -d parse_mode="Markdown"

    # 🔴 ЕСЛИ ТЕСТЫ УПАЛИ:
    - name: Send Telegram Failure Notification
      if: failure()
      run: |
        TEXT="❌ *Playwright Tests FAILED!*%0A%0A👤 *Поломал:* ${{ github.actor }}%0A🌿 *Ветка:* ${{ github.ref_name }}%0A📝 *Коммит:* ${{ github.event.head_commit.message }}%0A%0A🔍 *Логи и отчет:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOK }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_TO }}" \
          -d text="$TEXT" \
          -d parse_mode="Markdown"